export const CHURCHGROUPS = [
      { id: 0, name: 'ECO'},
      { id: 56, name: 'AJAX' },
      { id: 55, name: 'ARUBA' },
      { id: 51, name: 'Barrie' },
    //  { id: 46, name: 'Bas St Laurent' },
      { id: 27, name: 'Brampton' },
      { id: 19, name: 'Brantford' },
      { id: 18, name: 'Burlington' },
      { id: 47, name: 'CAMBRIDGE' },
      { id: 57, name: 'Chateauguay' },
      { id: 71, name: 'Chatham-Kent' },
      { id: 54, name: 'COLLINGWOOD' },
      { id: 45, name: 'COTE ST LUC' }, 
      { id: 70, name: 'Daveluyville' },
      { id: 22, name: 'Durham' },
      { id: 29, name: 'Etobicoke' },
      { id: 74, name: 'Edmonton AB' },
      { id: 35, name: 'GATINEAU' },
      { id: 14, name: 'GUELPH' },
      { id: 40, name: 'HALIFAX' },
      { id: 31, name: 'HAMILTON' }, 
      { id: 72, name: 'Happy Valley-Goose Bay' },
      { id: 34, name: 'KAMOURASKA' }, 
      { id: 15, name: 'KITCHENER' },
      { id: 68, name: 'LAVAL' },
      { id: 39, name: 'LEAMINGTON' }, 
      { id: 69, name: 'Listowel' },  
      { id: 12, name: 'LONDON' },
      { id: 17, name: 'MILTON' },
      { id: 28, name: 'Mississauga' },
      { id: 38, name: 'MONCTON' },
      { id: 36, name: 'MONTREAL' },
      { id: 26, name: 'Newmarket' },
      { id: 32, name: 'Niagara Falls' },
      { id: 52, name: 'North Calgary' },
      { id: 23, name: 'NORTH YORK' },
      { id: 40, name: 'NOVA SCOTIA' },
      { id: 16, name: 'OAKVILLE' },
      { id: 50, name: 'ORLEANS' },
      { id: 42, name: 'OTTAWA EAST' },
      { id: 43, name: 'OTTAWA WEST' },
      { id: 44, name: 'PRINCE EDWARD ISLAND' },
      { id: 25, name: 'Richmond Hill' },
      { id: 46, name: 'Saint-Laurent' },
      { id: 48, name: 'SARNIA' },
      { id: 20, name: 'Scarborough North' },
      { id: 21, name: 'Scarborough South' },
      { id: 53, name: 'South Calgary' },
      { id: 30, name: 'St.Catharines' },
      { id: 1, name: 'TORONTO' },  
      { id: 24, name: 'Vaughan' },
      { id: 73, name: 'Welland' }, 
      { id: 37, name: 'West Island' },
      { id: 49, name: 'Windsor' },    
 ];

export const TRIBES = [ 
        { id:0, name:'N/A' },
        { id:1, name:'Dan' },
        { id:2, name:'Issacar'},
        { id:3, name:'Judah'},
        { id:4, name:'Judah(Simeon)' },
        { id:5, name:'Levi'},
        { id:6, name:'Naphtali'},
        { id:7, name:'Naphtali(Scarb-North)'},
        { id:8, name:'Simeon'},
        { id:9, name:'Benjamin'},
        { id:10, name:'Zebulun' },
        { id:11, name:'Joseph' }
      ];